options:
  image:
    type: string
    default: "ibcndevs/limeds"
    description: |
      The default value will deploy the regular LimeDS docker image. If this refers to a docker image in a private repository, please provide the username and its corresponding secret.
